const LOAD_TASKS = "LOAD_TASKS";

const CREATE_TASK_ASYNC = "CREATE_TASK_ASYNC";
const DELETE_TASK_ASYNC = "DELETE_TASK_ASYNC";
const UPDATE_TASK_ASYNC = "UPDATE_TASK_ASYNC";
const LOAD_TASKS_ASYNC = "LOAD_TASKS_ASYNC";

export {LOAD_TASKS}
export {CREATE_TASK_ASYNC,DELETE_TASK_ASYNC,UPDATE_TASK_ASYNC,LOAD_TASKS_ASYNC}
