const express = require('express')
const errorHandler = require('./controllers/error_handler')
require('./config/db')
const taskRouter = require('./routes/task_router')
const cors = require('cors')
const port = process.env.PORT || 8080
const app = express()
app.use(cors())
app.use(express.json())
app.use("/tasks",taskRouter)
app.use(errorHandler)
app.listen(port,()=>console.log("server started"))